### ISSUE TITLE
Value Error : Running with hindi word embeddings

### ISSUE THREAD

**Issue by Killthebug** [ZhixiuYe/HSCRF-pytorch#1]
Hey, I'm running the code for binary labeling (I only have the MISC tag).

I'm working with 300 sized Hindi Word2Vec Embeddings.

Here's a pastebin of the error : https://pastebin.com/fDF2aTRD

Any inputs on how to resolve this?

**Comment by ZhixiuYe** [comment]
I have modified some code and you can download the code and try again.

**Comment by Killthebug** [comment]
So, it runs now but after running for one epoch produces the follow error : https://pastebin.com/WPB84pdv

**Comment by ZhixiuYe** [comment]
The code is written in Python 2.7 and pytorch 0.2.0. Maybe you are using pytorch 0.4.
