### ISSUE TITLE
 tried to construct a tensor

### ISSUE THREAD

**Issue by lijinjiang001** [ZhixiuYe/HSCRF-pytorch#11]
Traceback (most recent call last):
   File "/home/04-HSCRF-pytorch-master/train.py", line 210, in <module>
    evaluator.calc_score(model, dev_dataset_loader)
   File "/home/04-HSCRF-pytorch-master/evaluator.py", line 172, in calc_score
    decoded_crf, crf_result_scored_by_crf = utils.decode_with_crf(ner_model.crf, word_representations, mask_v,self.l_map)
  File "/home/04-HSCRF-pytorch-master/utils.py", line 777, in decode_with_crf
    bi_crf = torch.cuda.LongTensor(bi_crf).transpose(0,1).unsqueeze(2)
RuntimeError: tried to construct a tensor from a nested int sequence, but found an item of type numpy.int64 at index (0, 0)

**Comment by ZhixiuYe** [comment]
Do you use PyTorch 0.2.0?

**Comment by lijinjiang001** [comment]
Yes，I checked the "bi_crf = torch.cuda.LongTensor(bi_crf).transpose(0,1).unsqueeze(2)", and ran it singlely, it can work, but when I ran the full code, it was wrong.

**Comment by ZhixiuYe** [comment]
I think you can print `bi_crf` before line 776 and see what `bi_crf` is actually.
