### ISSUE TITLE
version of PyTorch

### ISSUE THREAD

**Issue by allanj** [ZhixiuYe/HSCRF-pytorch#13]
Is it possible to use PyTorch 0.4.0?

It seems I'm running into some issues but not sure if it dues to the version issue.

`allan@statnlp0:~/tmp/HSCRF-pytorch$ CUDA_VISIBLE_DEVICES=0 python train.py --char_lstm --high_way
seed:  5703958
setting:
Namespace(allowspan=6, batch_size=10, char_embedding_dim=30, char_lstm=True, char_lstm_hidden_dim=300, char_lstm_layers=1, checkpoint='./checkpoint/', clip_grad=5.0, cnn_filter_num=30, dev_file='./data/eng.testa', dropout_ratio=0.55, early_stop=10, emb_file='./data/glove.6B.100d.txt', epoch=150, grconv=False, high_way=True, highway_layers=1, index_embeds_dim=10, least_epoch=75, load_check_point='', load_opt=False, lr=0.015, lr_decay=0.05, mini_count=5, model_name='HSCRF', momentum=0.9, scrf_dense_dim=100, shrink_embedding=False, start_epoch=0, test_file='./data/eng.testb', train_file='./data/eng.train', unk='unk', word_embedding_dim=100, word_hidden_dim=300, word_lstm_layers=1)
loading corpus
constructing coding table
/home/allan/tmp/HSCRF-pytorch/model/utils.py:642: UserWarning: nn.init.uniform is now deprecated in favor of nn.init.uniform_.
  nn.init.uniform(input_embedding, -bias, bias)
constructing dataset
building model
/usr/local/lib/python2.7/dist-packages/torch/nn/modules/rnn.py:38: UserWarning: dropout option adds dropout after all but last recurrent layer, so non-zero dropout expects num_layers greater than 1, but got dropout=0.55 and num_layers=1
  "num_layers={}".format(dropout, num_layers))
/home/allan/tmp/HSCRF-pytorch/model/utils.py:649: UserWarning: nn.init.uniform is now deprecated in favor of nn.init.uniform_.
  nn.init.uniform(input_linear.weight, -bias, bias)
/home/allan/tmp/HSCRF-pytorch/model/hscrf_layer.py:60: UserWarning: nn.init.uniform is now deprecated in favor of nn.init.uniform_.
  nn.init.uniform(input_embedding, -bias, bias)
/home/allan/tmp/HSCRF-pytorch/model/hscrf_layer.py:68: UserWarning: nn.init.uniform is now deprecated in favor of nn.init.uniform_.
  nn.init.uniform(input_linear.weight, -bias, bias)
/home/allan/tmp/HSCRF-pytorch/model/utils.py:660: UserWarning: nn.init.uniform is now deprecated in favor of nn.init.uniform_.
  nn.init.uniform(weight, -bias, bias)
/home/allan/tmp/HSCRF-pytorch/model/utils.py:663: UserWarning: nn.init.uniform is now deprecated in favor of nn.init.uniform_.
  nn.init.uniform(weight, -bias, bias)
 - Tot it 1404 (epoch 0): 0it [00:00, ?it/s]train.py:180: UserWarning: torch.nn.utils.clip_grad_norm is now deprecated in favor of torch.nn.utils.clip_grad_norm_.
  nn.utils.clip_grad_norm(model.parameters(), args.clip_grad)
 - Tot it 1404 (epoch 0): 0it [00:00, ?it/s]train.py:195: UserWarning: torch.nn.utils.clip_grad_norm is now deprecated in favor of torch.nn.utils.clip_grad_norm_.
  nn.utils.clip_grad_norm(model.parameters(), args.clip_grad)
epoch_loss:  22.3492750524                         
/home/allan/tmp/HSCRF-pytorch/model/data_packer.py:49: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  f_f = Variable(f_f[:, 0:mlen[0]].transpose(0, 1), volatile=True).cuda()
/home/allan/tmp/HSCRF-pytorch/model/data_packer.py:50: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  f_p = Variable(f_p[:, 0:mlen[1]].transpose(0, 1), volatile=True).cuda()
/home/allan/tmp/HSCRF-pytorch/model/data_packer.py:51: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  b_f = Variable(b_f[:, -mlen[0]:].transpose(0, 1), volatile=True).cuda()
/home/allan/tmp/HSCRF-pytorch/model/data_packer.py:52: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  b_p = Variable((b_p[:, 0:mlen[1]] - ocl + mlen[0]).transpose(0, 1), volatile=True).cuda()
/home/allan/tmp/HSCRF-pytorch/model/data_packer.py:53: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  w_f = Variable(w_f[:, 0:mlen[1]].transpose(0, 1), volatile=True).cuda()
/home/allan/tmp/HSCRF-pytorch/model/data_packer.py:54: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  tg_v = Variable(target[:, 0:mlen[1]].transpose(0, 1), volatile=True).unsqueeze(2).cuda()
/home/allan/tmp/HSCRF-pytorch/model/data_packer.py:55: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  mask_v = Variable(mask[:, 0:mlen[1]].transpose(0, 1), volatile=True).cuda()
/home/allan/tmp/HSCRF-pytorch/model/data_packer.py:56: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  SCRF_labels = Variable(SCRF_labels[:, 0:mlen[2]], volatile=True).cuda()
/home/allan/tmp/HSCRF-pytorch/model/data_packer.py:57: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  mask_SCRF_laebls = Variable(mask_SCRF_laebls[:, 0:mlen[2]], volatile=True).cuda()
/home/allan/tmp/HSCRF-pytorch/model/data_packer.py:58: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  cnn_features = Variable(cnn_features[:, 0:mlen[1], 0:mlen[3]].transpose(0, 1), volatile=True).cuda().contiguous()
/home/allan/tmp/HSCRF-pytorch/model/crf_layer.py:113: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  mask = Variable(1 - mask.data, volatile=True)
/home/allan/tmp/HSCRF-pytorch/model/crf_layer.py:114: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  decode_idx = Variable(torch.cuda.LongTensor(seq_len-1, bat_size), volatile=True)
Traceback (most recent call last):
  File "train.py", line 205, in <module>
    evaluator.calc_score(model, dev_dataset_loader)
  File "/home/allan/tmp/HSCRF-pytorch/model/evaluator.py", line 172, in calc_score
    decoded_crf, crf_result_scored_by_crf = utils.decode_with_crf(ner_model.crf, word_representations, mask_v,self.l_map)
  File "/home/allan/tmp/HSCRF-pytorch/model/utils.py", line 763, in decode_with_crf
    decoded_crf = crf.decode(word_reps, mask_v)
  File "/home/allan/tmp/HSCRF-pytorch/model/crf_layer.py", line 131, in decode
    decode_idx[idx] = pointer
RuntimeError: expand(torch.cuda.LongTensor{[50, 1]}, size=[50]): the number of sizes provided (1) must be greater or equal to the number of dimensions in the tensor (2)`

**Comment by ZhixiuYe** [comment]
Sorry, I'm not familar with PyTorch 0.4.0. You can try 0.2.0 firstly and see whether the code works.

**Comment by zhoujianch** [comment]
on RuntimeError, because the current pointer is torch.Size([50,1]), you need to change it to torch.Size([50]).for example,you can use code 'pointer = pointer.squeeze(1)',before code 'decode_idx[idx] = pointer'
