### ISSUE TITLE
Can you offer me the check point files?

### ISSUE THREAD

**Issue by zamhown** [ZhixiuYe/HSCRF-pytorch#17]
When I try to run 'eval.py', I realize that there is lack of './checkpoint/6365035.json' and './checkpoint/6365035.model' file in this code source. Does this project need these two files? I will be grateful if you can offer me more information.

**Comment by ZhixiuYe** [comment]
You can train a model firstly by this command line:
```
CUDA_VISIBLE_DEVICES=0 python train.py --char_lstm --high_way
```
and then `eval`.

**Comment by zamhown** [comment]
Thank you! I have trained this model but I forgot creating the './checkpoint' folder before running this command.
