### ISSUE TITLE
out of memory

### ISSUE THREAD

**Issue by amoursmile** [ZhixiuYe/HSCRF-pytorch#18]
Have you ever had this problem:
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/condabld/pytorch_1511304568725/work/torch/lib/THC/generic/THCStorage.cu:66

I used the Chinese corpus with the vector dimension of 300. I try to use the little dataset and make the batchsize = 5, but it failed again.

**Comment by ZhixiuYe** [comment]
Maybe you can try not to use language model for char embedding and only type this command `CUDA_VISIBLE_DEVICES=0 python train.py`.

**Comment by amoursmile** [comment]
Thanks. I did as you suggested, but it still out of memory. I can't find the cause.

**Comment by ZhixiuYe** [comment]
Can you run the code with English corpus successfully ?

**Comment by amoursmile** [comment]
yes, it works with the English corpus. I found that the loss is too big with the Chinese corpus.
