### ISSUE TITLE
hard-coded dimensions of view cnn_lstm

### ISSUE THREAD

**Issue by udion** [ZhixiuYe/HSCRF-pytorch#3]
in the cnn_lstm function in `word_rep_layer.py` you've hard-coded the dimensions in the view of  `d_char_out`, that is you are using `(-1, self.batch_size, 30) `, it should be `(word_seq.size(0), slef.batch_size, -1)` to make it general

I think this won't work if you change the embedding dimension or number of characters in alphabet

**Comment by ZhixiuYe** [comment]
Thanks, I have fixed it.
