### ISSUE TITLE
What is the format of the dataset?

### ISSUE THREAD

**Issue by udion** [ZhixiuYe/HSCRF-pytorch#7]
the dataset given by you in data folder has sentences such as 
```
AUGUST RB I-NP O
1996 CD I-NP O
CDU NNP I-NP I-ORG
/ SYM O I-ORG
CSU NNP I-NP I-ORG
SPD NNP I-NP B-ORG
FDP NNP I-NP B-ORG
Greens NNP I-NP B-ORG
PDS NNP I-NP B-ORG
```
this is not BIO as B is following I, it should have been B-ORG followed by multiple I-ORG, same happens with B-MISC and B-PER and B-LOC doesn't even exits. please clarify

**Comment by ZhixiuYe** [comment]
There are two kinds of BIO formats. http://www.aclweb.org/anthology/W03-0419 . You can refer to this paper for detail data format introduction.

**Comment by udion** [comment]
Thanks for the response
