### ISSUE TITLE
Goldfactors format

### ISSUE THREAD

**Issue by sebastianGehrmann** [ZhixiuYe/HSCRF-pytorch#8]
Hi, I have been trying to use your code as a reference to implement a similar SCRF variant, and am a little confused by the `get_logloss_numerator` function. What exactly is the goldfactors you use for the correct path scores?
I am speaking about this line: https://github.com/ZhixiuYe/HSCRF-pytorch/blob/master/model/hscrf_layer.py#L146

Could you give me an example how I can generate my own factors? 

========><==========
EDIT: I think I understand the format, each item is a tensorized list of (from_id, to_id, prev_tag, curr_tag). If that is correct, the comment that the size is `(batch_size, tag_len, 4)` is confusing, since it means the maximum number of unique tag-sequences within items in the batch. I assumed that tag_len means tagset_size.

**Comment by ZhixiuYe** [comment]
Yes, 4 means `(from_id, to_id, prev_tag, curr_tag)`, but `tag_len` is not `tagset_size`. `target_size` is 7 in this task `PER, LOC, ORG, MISC, <START>, <STOP> and O`, and `tag_len` is the max SCRF label length of a batch of sentences. 
For example, if batch_size is 1 and a label sequence in CRF style is `[B-PER, E-PER, O, S-LOC]` , the SCRF-style labels should be `[(1, 2, <START>, PER), (3, 3, PER, O), (4, 4,O,  LOC)]` and `tag_len` should be 3.

**Comment by sebastianGehrmann** [comment]
Thanks! I got it then.
